name: Navion Insurance
favicon: null
layout_spectrum: 0.74731
typography_spectrum: 0.44406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe7e0'
    - '#11386e'
    - '#929697'
    - '#556e91'
    - '#bac0c6'
  brandStrength: 0.4653784839902073
  lightness: 0.9577294234186411
  saturation: 0.50886309472844
  rhythmicContrast: 0.48487453698180616
purpose: []
