name: Navion Insurance
favicon: null
layout_spectrum: 0.7533255817834288
typography_spectrum: 0.39108380977995694
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4653784839902073
  lightness: 0.9577294234186411
  saturation: 0.50886309472844
  rhythmicContrast: 0.48487453698180616
purpose: []
